# Generated by Django 4.0.5 on 2022-07-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='input',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
